### ISSUE TITLE
hyperlink in YAML block

### ISSUE THREAD

**Issue by bianchini88** [elixir-europe-training/ELIXIR-TrP-FAIR-Converge#144]
There are hyperlinks in the YAML block (i.e. the table) on https://elixir-europe-training.github.io/ELIXIR-TrP-FAIR-Converge/units/FAIR-generics/topics/1-why-fair/ which do not render. Is rendering of these not supported at all? Do you have any idea @martijnkersloot?

**Comment by martijnkersloot** [comment]
Fixed by moving to Jekyll!
